### ISSUE TITLE
Installation in-chapter anchors don't work in translations

### ISSUE THREAD

**Issue by magul** [DjangoGirls/tutorial#1595]
### Issue description

Installation in-chapter anchors were introduced in #1508. It uses markdown titles as anchor identification (so if we have a subchapter named `Set up virtualenv and install Django` we need to set anchor to `#set-up-virtualenv-and-install-django`).

Unfortunately, when the tutorial is translated, we tend to translate subchapter titles but anchors are not exposed to be translated. That results (e.g. in German translation to have title `Virtualenv einrichten und Django installieren` but anchor still `#set-up-virtualenv-and-install-django`).

### Language

all but not `en`

The issue has been fixed for:

* [ ] [🇨🇿 Čeština (beta)](cs/)
* [ ] [🇩🇪 Deutsch](de/) (PR #1602)
* [ ] [🇬🇷 Ελληνικά (beta)](el/)
* [ ] [🇪🇸 Español (beta)](es/) (PR #1602)
* [ ] [🇮🇷 فارسی (beta)](fa/)
* [ ] [🇫🇷 Français (beta)](fr/) (PR #1602)
* [ ] [🇭🇺 Magyar (beta)](hu/)
* [ ] [🇮🇹 Italiano (beta)](it/)
* [ ] [🇯🇵 日本語](ja/) (PR #1602)
* [ ] [🇰🇵/🇰🇷 한국어 (beta)](ko/)
* [ ] [🇵🇱 Polski](pl/)
* [ ] [🇧🇷 Português-brasileiro](pt/) (PR #1602)
* [ ] [🇷🇺 Русский (beta)](ru/)
* [ ] [🇸🇰 Slovenčina (beta)](sk/)
* [ ] [🇹🇷 Türkçe (beta)](tr/)
* [ ] [🇺🇦 Українська](uk/)
* [ ] [🇨🇳 简体中文](zh/)

### Operating system

all

**Comment by sarajoha** [comment]
Hi! If it's ok I'd like to help with this one. Just to be sure, what is needed it's to fix the anchor, by translating it, so it points to the section, right? Please correct me if I'm wrong. 
Also, if I'm right what is the best way to do it? A PR per language or all in one PR?

**Comment by das-g** [comment]
I'm unsure how this can be fixed for good. If we just change it for the translations on GitHub, it would be overwritten by re-importing new translations from Crowdin, unless we take special precautions to not do that somehow.

Though, as we do all translation re-imports through pull requests, too, it'd probably be noticed there and could be fixed. (Changes to the table of contents aren't that common, so this would only be a minor maintenance nuisance.)

Therefore, I think we we may proceed to fix this on GitHub and we'll care about the consequences for new-translation-version-integration later.

**Comment by das-g** [comment]
> Hi! If it's ok I'd like to help with this one.

Cool! Thank you, @sarajoha! :heart:

> Just to be sure, what is needed it's to fix the anchor, by translating it, so it points to the section, right?

This sounds correct. :+1:

To see what the anchor ID looks like (MarkDown does some mangling, to get rid of spaces and some special characters), have a look on GitHub at the installation chapter in the respective language (e.g. https://tutorial.djangogirls.org/de/installation/ for German) and hover over a section title. A "#" will appear next to it that links to the respective section.

> Also, if I'm right what is the best way to do it? A PR per language or all in one PR?

If you can do that all in one go, one PR is fine. But if that's too much to do at once, feel free to split it up into several PRs, e.g. one per language or one per subsection (for all languages).

**Comment by sarajoha** [comment]
> Cool! Thank you, @sarajoha! 

No problem :blush: 

> To see what the anchor ID looks like (MarkDown does some mangling, to get rid of spaces and some special characters), have a look on GitHub at the installation chapter in the respective language (e.g. https://tutorial.djangogirls.org/de/installation/ for German) and hover over a section title. A "#" will appear next to it that links to the respective section.
>
Thanks for the tip!
  
> If you can do that all in one go, one PR is fine. But if that's too much to do at once, feel free to split it up into several PRs, e.g. one per language or one per subsection (for all languages).

I think I'll batch it, I'll do like 5 languages per PR if that's ok.

**Comment by das-g** [comment]
> I think I'll batch it, I'll do like 5 languages per PR if that's ok.

Sure, as long as each PR in itself is consistent and an improvement / fix.

**Comment by das-g** [comment]
Please mention this issue (#1599) in PRs that fix part of it.

I've added checkboxes to the description of this issue, so that we can track which languages have received a fix for this problem.

**Comment by das-g** [comment]
> Maybe that will solve that issue? https://www.markdownguide.org/extended-syntax/#heading-ids

Does GitBook legacy support explicit heading IDs? If so, adding them (and changing the links accordingly) could indeed be a permanent solution.

**Comment by magul** [comment]
> Does GitBook legacy support explicit heading IDs? If so, adding them (and changing the links accordingly) could indeed be a permanent solution.

That should be tested. Do you want to test that @sarajoha ?

**Comment by das-g** [comment]
Testing it probably involves running GitBook locally, doesn't it?

**Comment by magul** [comment]
Didn't think about locally testing, but that should also reveal if the support it or not. I was actually thinking about pushing new code to GitBook Legacy service.

**Comment by sarajoha** [comment]
> That should be tested. Do you want to test that @sarajoha ?

Yes, I'd like to test that @magul.

**Comment by sarajoha** [comment]
Hi @magul, I've been trying to use GitBook Legacy but I can't create an account there, it sends me to the new GitBook page. I created the GitBook account on the new page but I won't let me log in to the Legacy version.

When I try to login into Legacy I get this error:
![image](https://user-images.githubusercontent.com/19717889/67296986-dcf45e00-f4ae-11e9-8412-3c1c1d9acd76.png)

😕 do you have any ideas about how I could test in GitBook Legacy?

**Comment by das-g** [comment]
I think @magul's idea was to just create a new pull request that makes the changes we assume to work:

- introduce explicit section IDs in the installation chapter
- link to the corresponding anchors from the table of contents

... and then (instead of #1602 etc.) just merge that new pull request (which will trigger a rebuild on GitBook legacy) and see whether the result (which will automatically be deployed to tutorial.djangogirls.org) works correctly. If not, we can just revert the pull request or try something else. (As the links already don't work, there's not much chance of making it even worse, so it's OK if we test this out "in production".)

Can you make such a pull request, @sarajoha ?

**Comment by sarajoha** [comment]
Oh, I get it now. Yes, I can make that PR @das-g

**Comment by sarajoha** [comment]
Is it okay if I just do it for language to see if it works? @das-g

**Comment by das-g** [comment]
> Is it okay if I just do it for language to see if it works? @das-g

You mean just for _one_ language? Sure! (We should probably do it just for English, anyway, and then let @magul re-import the translations from Crowdin that will hopefully contain the change automatically.)

**Comment by magul** [comment]
I've just created #1608 which properly populates French translation with custom id.

**Comment by magul** [comment]
Closing that one as custom ids work properly. Well done!
